version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_auth_app_dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/nestauth?schema=public"
      JWT_SECRET: "super-secret"
      JWT_REFRESH_SECRET: "refresh-secret"
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data_dev:
