FROM node:20-alpine

WORKDIR /usr/src/app

RUN apk add --no-cache python3 make g++ openssl

COPY package*.json ./

RUN npm install

RUN npm install -g @nestjs/cli

RUN npm install -g prisma@5.0.0

COPY .env .env

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
