version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres_prod
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestauth
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest_auth_app_prod
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/nestauth?schema=public"
      JWT_SECRET: "super-secret"
      JWT_REFRESH_SECRET: "refresh-secret"
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node dist/main.js"

volumes:
  postgres_data_prod:
