version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest_auth_app_dev
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      # ❌ KHÔNG mount node_modules để tránh lỗi Prisma bị lệch binary
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"
      WATCHPACK_POLLING: "true"
      NODE_ENV: development
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/nest_auth_dev?schema=public"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: nest_postgres_dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_auth_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: nest_adminer_dev
    restart: always
    ports:
      - "8080:8080"

volumes:
  postgres_data_dev:
